In [1]:
# import pandas
import sys
print(sys.executable)

c:\Program Files\Python39\python.exe

In [22]:
!pip install pandas
!pip install openxls
!pip install xlrd

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\pc\appdata\roaming\python\python39\site-packages (1.4.3)
Requirement already satisfied: numpy>=1.18.5 in c:\users\pc\appdata\roaming\python\python39\site-packages (from pandas) (1.23.1)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\pc\appdata\roaming\python\python39\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\pc\appdata\roaming\python\python39\site-packages (from pandas) (2022.1)
Requirement already satisfied: six>=1.5 in c:\users\pc\appdata\roaming\python\python39\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Defaulting to user installation because normal site-packages is not writeable

ERROR: Could not find a version that satisfies the requirement openxls (from versions: none)
ERROR: No matching distribution found for openxls

Defaulting to user installation because normal site-packages is not writeable
Collecting xlrd
  Downloading xlrd-2.0.1-py2.py3-none-any.whl (96 kB)
     -------------------------------------- 96.5/96.5 kB 690.3 kB/s eta 0:00:00
Installing collected packages: xlrd
Successfully installed xlrd-2.0.1

In [24]:
import pandas as pd
import openpyxl

import xlrd

In [38]:
# df = pd.DataFrame(pd.read_excel("./excel/CAV DEALER - 7-26-22 New Price Sheet for Distribution.xlsx"))
xls = pd.ExcelFile("./excel/CAV DEALER - 7-26-22 New Price Sheet for Distribution.xlsx")
df1 = pd.read_excel(xls, '3. E-Vision Series')
# df2 = pd.read_excel(xls, 'Sheet2')

# sheet = xlrd.open_workbook("./excel/CAV DEALER - 7-26-22 New Price Sheet for Distribution.xlsx").sheet_by_index(2)

In [39]:
df1

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,NaN,MSRP Price Updated 6-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,E-Vision LASER series,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,E-Vision LASER Models = 20000 hour laser illum...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
91,1. With the exception of the E-Vision 5100 and...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92,2. Upgrade to 5 Year Warranty is for Standard ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93,All Prices in US dollars.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94,Prices and specifications subject to change wi...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Date updated
95,"DP V60 7/12/2022 © Digital Projection, Inc.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
xls.sheet_names

['1. Cover & T of C',
 "2. How to Spec & Write P.O.'s  ",
 '3. E-Vision Series',
 '4. M-Vision Series',
 '5. TITAN Series',
 '6. INSIGHT 8K',
 '8. Accessories & Legacy Lamps',
 '9. Demo, Freight and Service',
 '10. Value Add Services ',
 '11. Product Warranty',
 '12. Extended Warranty',
 '13. DP Contacts']

In [48]:
df3 = xls.parse(2, header=18)
df3

,LASER-Based Systems1,lumens / contrast,Part #,List Price,1-5 Units,6-19 Units,20+ Units / Reg,Unnamed: 7,MSRP,Dlr Cost,Unnamed: 10
0,E-Vision LASER (1920 x 1200 native) NOTE: E-...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"To order use part # ""5YR-WRT""",NaN,NaN
1,E-Vision 4000 4K_UHD*,"3,800 / 1200:1",121-804,8425,6066,5897.5,5729,NaN,1011,758.25,NaN
2,Special Order E-Vision LASER 5100 **,"5100 / 2,000:1",120-552,6325,4554,4427.5,4301,NaN,759,569.25,NaN
3,E-Vision LASER 5900 ***,"6,000 / 2,000:1",120-551,6125,4410,4287.5,4165,NaN,735,551.25,NaN
4,E-Vision LASER 6500 II ****,"6,500 / 5,000:1",120-061,9995,7196.4,6996.5,6796.6,NaN,1199.4,899.55,NaN
...,...,...,...,...,...,...,...,...,...,...,...
73,1. With the exception of the E-Vision 5100 and...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74,2. Upgrade to 5 Year Warranty is for Standard ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,All Prices in US dollars.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,Prices and specifications subject to change wi...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Date updated
77,"DP V60 7/12/2022 © Digital Projection, Inc.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN